[package]
name = "init"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.19"
nix = "0.26.2"
thiserror = "1.0.44"

[profile.release]
lto = true
